'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    'sınıfı tarafından otomatik olarak oluşturuldu.
    'Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    'komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    '''<summary>
    '''  Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LoadTubes.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        '''  CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property close_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property close_throw_bottom_lr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_throw_bottom_lr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property download_icon212() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download_icon212", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property folder2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property fullscreen_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fullscreen_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property music_notes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("music_notes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property quest_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quest_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property sandclock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sandclock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property unknowmusic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unknowmusic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
